name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: running unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      SOLANA_VERSION: v1.4.3
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cargo install rustfilt || true
          sh -c "$(curl -sSfL https://release.solana.com/$SOLANA_VERSION/install)"
          echo "PATH=/home/runner/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          cargo build-bpf --version
      - run: yarn install
      - run: yarn test
        env:
          CI: true
  style:
    name: code style check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn add prettier --D
      - run: yarn style:check
